import { Hono } from 'hono';
import { Env } from '../types';
import { getCookie, setCookie } from 'hono/cookie';
import { sign } from 'hono/jwt';
import * as OTPAuth from 'otpauth';

const loginRoute = new Hono<{ Bindings: Env }>();

loginRoute.get('/login', (c) => {
	const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Login</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; background: #0f172a; color: #f8fafc; min-height: 100vh; margin: 0; display: flex; align-items: center; justify-content: center; overflow: hidden; }
        .glass { background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px); border: 1px solid rgba(255, 255, 255, 0.08); box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5); }
        .input-glass { background: rgba(15, 23, 42, 0.5); border: 1px solid rgba(255, 255, 255, 0.1); color: white; transition: all 0.2s; }
        .input-glass:focus { border-color: #34d399; outline: none; box-shadow: 0 0 0 2px rgba(52, 211, 153, 0.2); }
    </style>
</head>
<body class="relative">
    <div class="fixed top-[-15%] left-[-10%] w-[50vw] h-[50vw] rounded-full bg-blue-600/20 blur-[120px] pointer-events-none z-0"></div>
    <div class="fixed bottom-[-15%] right-[-10%] w-[50vw] h-[50vw] rounded-full bg-emerald-600/10 blur-[120px] pointer-events-none z-0"></div>

    <div class="glass w-full max-w-md p-10 rounded-3xl relative z-10 text-center mx-4">
        <div class="w-16 h-16 mx-auto bg-gradient-to-tr from-emerald-400 to-cyan-500 rounded-2xl flex items-center justify-center mb-6 shadow-lg shadow-emerald-500/30">
            <svg class="w-8 h-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/></svg>
        </div>
        <h1 class="text-3xl font-bold mb-2">Secure Access</h1>
        <p class="text-slate-400 mb-6 text-sm">Enter the Google Authenticator code generated by your app.</p>
        
        <form action="/login" method="POST" class="space-y-6">
            <div>
                <input type="text" name="code" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required placeholder="123456" class="w-full text-center text-3xl tracking-[0.5em] input-glass rounded-xl px-4 py-4 placeholder:text-slate-600 text-emerald-300 font-mono shadow-inner">
            </div>
            <button type="submit" class="w-full bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-semibold py-3.5 rounded-xl transition-all shadow-lg hover:shadow-emerald-500/25">
                Authenticate
            </button>
            <script>
                const params = new URLSearchParams(window.location.search);
                if (params.has('error')) {
                    document.write('<div class="mt-4 text-red-400/90 text-sm font-medium bg-red-500/10 border border-red-500/20 py-2 rounded-lg">Authentication Failed [' + params.get('error') + ']</div>');
                }
            </script>
        </form>
    </div>
</body>
</html>`;
	return c.html(html);
});

loginRoute.post('/login', async (c) => {
	const body = await c.req.parseBody();
	const code = (body.code as string || '').trim();

	if (!code || code.length !== 6) {
		return c.redirect('/login?error=length');
	}

	// Safety check for secrets
	if (!c.env.MFA_SECRET || !c.env.JWT_SECRET) {
		console.error(`[Login] Missing Critical Secrets: MFA_SECRET=${!!c.env.MFA_SECRET}, JWT_SECRET=${!!c.env.JWT_SECRET}`);
		return c.redirect('/login?error=missing_secrets_on_server');
	}

	// Initialize TOTP verifier
	let totp = new OTPAuth.TOTP({
		issuer: "KnowledgeAssistant",
		label: "Dashboard",
		algorithm: "SHA1",
		digits: 6,
		period: 30,
		secret: OTPAuth.Secret.fromBase32(c.env.MFA_SECRET)
	});

	// Validate the token (window 10 = checks current + 10 windows forward/backward. That's 5 FULL MINUTES of drift allowance!)
	let delta = totp.validate({ token: code, window: 10 });

	if (delta !== null) {
		try {
			// Valid MFA! Mint a 24-hour JSON Web Token session using securely provided random secret.
			const token = await sign({ user: 'admin', exp: Math.floor(Date.now() / 1000) + (60 * 60 * 24) }, c.env.JWT_SECRET, 'HS256');
			setCookie(c, 'auth_session', token, {
				path: '/',
				secure: true,
				httpOnly: true,
				maxAge: 60 * 60 * 24 // 24 hours
			});
			return c.redirect('/dashboard');
		} catch (e: any) {
			return c.redirect('/login?error=jwt_signing_failed');
		}
	}

	// Invalid fallback
	return c.redirect(`/login?error=invalid_totp_recheck_secret_used_${code}`);
});

export default loginRoute;
